{% set name = "mesas" %}
{% set version = "1.20241002" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charman2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4147f2da2e7c662970757ba7350dc98a1aeaf72c39c25a531b211dba2e126240

build:
  number: 1
  skip: true  # [py==37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy[version='>=1.22']                # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - {{ compiler('m2w64-toolchain') }}  # [win]
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - matplotlib[version='>=3.3.0']
    - meson=1.3.2
    - pandas[version='>=1.1.0']
    - pytest[version='>=6.0.1']
    - scipy[version='>=1.3.1']
    - gfortran
  host:
    - python
    - pip
    - numpy[version='>=1.22']
  run:
    - python
    - pandas
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base

test:
  imports:
    - mesas
    - mesas.sas.solve

about:
  home: http://github.com/charman2/mesas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: multiresolution estimation of storage selection

  description: |
    mesas is a suite of tools for analyzing tracer data and modeling solute
    transport in time-variable input-output flow systems. It is written in python wrapping
    a fortran extension where the serious number-crunching happens
  doc_url: http://mesas.readthedocs.io/
  dev_url: https://github.com/charman2/mesas

extra:
  recipe-maintainers:
    - charman2
