{% set name = "mesas" %}
{% set version = "0.2020.0805" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charman2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 97ce139d2180ad9415dc6debfe16946483365bf1151095bd3dba7abb51da1f03

build:
  number: 2
  script:
    - export LDFLAGS="$LDFLAGS -v"    # [osx]
    - "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy 1.18.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - matplotlib-base

test:
  imports:
    - mesas

about:
  home: http://github.com/charman2/mesas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'multiresolution estimation of storage selection'

  description: |
    mesas is a suite of tools for analyzing tracer data and modeling solute
    transport in time-variable input-output flow systems. It is written in python wrapping
    a fortran extension where the serious number-crunching happens
  doc_url: http://mesas.readthedocs.io/
  dev_url: https://github.com/charman2/mesas

extra:
  recipe-maintainers:
    - charman2
 
