{% set name = "mesas" %}
{% set version = "0.2021.0811" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charman2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fbdc1e633336c8da5c6896cfc0d1454a73ff6bb51bc97806e89b5d8192fd6162

build:
  number: 0
  script:
    - export LDFLAGS="$LDFLAGS -v"    # [osx]
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy 1.18.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - matplotlib-base

test:
  imports:
    - mesas

about:
  home: http://github.com/charman2/mesas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: multiresolution estimation of storage selection

  description: |
    mesas is a suite of tools for analyzing tracer data and modeling solute
    transport in time-variable input-output flow systems. It is written in python wrapping
    a fortran extension where the serious number-crunching happens
  doc_url: http://mesas.readthedocs.io/
  dev_url: https://github.com/charman2/mesas

extra:
  recipe-maintainers:
    - charman2

