{% set name = "mesas" %}
{% set version = "0.2021.0813" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charman2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1675784be0b12f36bb2d60c509ae9ca1e556c742741a924443f8a7dec5d9f906

build:
  number: 1
  script:
    - export LDFLAGS="$LDFLAGS -v"    # [osx]
    - "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy 1.21.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - matplotlib-base

test:
  imports:
    - mesas
  requires:
    - pytest
  commands:
    - pytest --pyargs mesas
    
about:
  home: http://github.com/charman2/mesas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'multiresolution estimation of storage selection'

  description: |
    mesas is a suite of tools for analyzing tracer data and modeling solute
    transport in time-variable input-output flow systems. It is written in python wrapping
    a fortran extension where the serious number-crunching happens
  doc_url: http://mesas.readthedocs.io/
  dev_url: https://github.com/charman2/mesas

extra:
  recipe-maintainers:
    - charman2
 
