{% set name = "mesas" %}
{% set version = "0.2022.0421" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charman2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cb41b8595f3cc7fa58015fc6c6d2abb910dcc2c34895863fd2c5f09ac7075b4e
  patches:
    - remove_cdflib90_sources.patch  # don't build cdflib90 files with extension
    - relative_import_of_solve_ext.patch  # import solve as .solve

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - numpy 1.21.*
  run:
    - python
    - pandas
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base

test:
  imports:
    - mesas
    - mesas.sas.solve

about:
  home: http://github.com/charman2/mesas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: multiresolution estimation of storage selection

  description: |
    mesas is a suite of tools for analyzing tracer data and modeling solute
    transport in time-variable input-output flow systems. It is written in python wrapping
    a fortran extension where the serious number-crunching happens
  doc_url: http://mesas.readthedocs.io/
  dev_url: https://github.com/charman2/mesas

extra:
  recipe-maintainers:
    - charman2
