{% set name = "mesas" %}
{% set version = "1.20240418" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charman2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 89457f747693a0fdd6c285401af274a2356aab69b3efaa54558d6d92a1cf4ee1

build:
  number: 2
  skip: true  # [py==37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy 1.24.*                           # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - {{ compiler('m2w64-toolchain') }}  # [win]
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - numpy 1.24.*
  run:
    - python
    - pandas
    - scipy
    - matplotlib-base

test:
  imports:
    - mesas
    - mesas.sas.solve

about:
  home: http://github.com/charman2/mesas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: multiresolution estimation of storage selection

  description: |
    mesas is a suite of tools for analyzing tracer data and modeling solute
    transport in time-variable input-output flow systems. It is written in python wrapping
    a fortran extension where the serious number-crunching happens
  doc_url: http://mesas.readthedocs.io/
  dev_url: https://github.com/charman2/mesas

extra:
  recipe-maintainers:
    - charman2
