{% set name = "mesas" %}
{% set version = "1.20240328" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charman2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3241a5fac6ad3755e950b6ff14399e570c713014a9b65718d799de0b55364ae7

build:
  number: 0
  skip: true  # [win and vc<14]
  skip: true  # [py==37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy 1.24.*                           # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - numpy 1.24.*
  run:
    - python
    - pandas
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base

test:
  imports:
    - mesas
    - mesas.sas.solve

about:
  home: http://github.com/charman2/mesas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: multiresolution estimation of storage selection

  description: |
    mesas is a suite of tools for analyzing tracer data and modeling solute
    transport in time-variable input-output flow systems. It is written in python wrapping
    a fortran extension where the serious number-crunching happens
  doc_url: http://mesas.readthedocs.io/
  dev_url: https://github.com/charman2/mesas

extra:
  recipe-maintainers:
    - charman2
